apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fia-arbeidsgiver-frontend
  namespace: pia
  labels:
    team: pia
  annotations:
    nginx.ingress.kubernetes.io/limit-rpm: "250"
spec:
  ingresses:
    - https://fia-arbeidsgiver.ekstern.dev.nav.no
  image: {{image}}
  port: 3000
  replicas:
    max: 2
    min: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: 02b25498-1a81-45b5-84cb-876a8899c809
          - id: e00f4248-2d26-4645-bf94-22d47623a51e
          - id: 30f17df5-c36c-4ad7-b862-48f56c95ebb2
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /*/deltaker
        - /*/deltaker/**
        - /api/*/deltaker/**
        - /api/bli-med
  accessPolicy:
    outbound:
      rules:
        - application: fia-arbeidsgiver
  env:
    - name: FIA_ARBEIDSGIVER_HOSTNAME
      value: fia-arbeidsgiver
    - name: FIA_SUPERBRUKER_GROUP_ID
      value: 02b25498-1a81-45b5-84cb-876a8899c809
    - name: FIA_SAKSBEHANDLER_GROUP_ID
      value: e00f4248-2d26-4645-bf94-22d47623a51e
    - name: FIA_LESETILGANG_GROUP_ID
      value: 30f17df5-c36c-4ad7-b862-48f56c95ebb2
