ingress: https://fia-arbeidsgiver.nav.no
fiaSuperbrukerGroup: f71a0eed-1e59-4b19-ae13-6c1af824fe8e
fiaSaksbehandlerGroup: a72547f2-c92b-420c-b7b0-fc227337e9ea
faroUrl: https://telemetry.nav.no/collect