server:
  log_level: info

metrics:
  wal_directory: /agent/wal
  global:
    scrape_interval: 1m
  configs:
    - name: default
logs:
  positions_directory: /agent/loki-pos
  configs:
    - name: default
      scrape_configs: []
      clients:
        - url: http://loki:3100/loki/api/v1/push
traces:
  # https://grafana.com/docs/tempo/latest/setup/set-up-test-app/#set-up-remote_write-to-your-tempo-cluster
  configs:
    - name: default
      remote_write:
        - endpoint: tempo:4317
          insecure: true
          protocol: grpc
      receivers:
        otlp:
          protocols:
            grpc:
            http:
              cors:
                max_age: 7200
                allowed_origins:
                  - '*'
integrations:
  metrics:
    autoscrape:
      enable: true
      metrics_instance: 'default'
  app_agent_receiver_configs:
    - autoscrape:
        enable: true
        metrics_instance: 'default'
      #api_key: 'secret' # FIXME. optional, if set, client will be required to provide it via x-api-key header
      instance: 'frontend'
      logs_instance: 'default'
      traces_instance: 'default'
      server:
        host: 0.0.0.0
        port: 12347
        cors_allowed_origins:
          - '*'
      logs_labels: # labels to source or override; will be added to loki log record
        stack: faro
        app_name: ""
        kind: ""
      logs_send_timeout: 5000
      sourcemaps:
        download: true # will download source file, extract source map location,
