name: Build, test and deploy
run-name: Build and deploy app || ${{ github.event.head_commit.message }}
on:
  # Allow updating playwright snapshots during manual runs
  workflow_call:
    inputs:
      update-snapshots:
        description: "Update playwright snapshots?"
        type: boolean

env:
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run tests and linting
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.9
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun lint
      - name: Run testing-library tests
        run: bun run test
      - name: Put host.docker.internal i hosts
        run: sudo echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts
      - run: bunx playwright install --with-deps
      - name: Set up cache for playwright screenshots
        id: cache
        uses: actions/cache@v4
        with:
          key: cache/${{github.repository}}/${{github.ref}}
          restore-keys: cache/${{github.repository}}/refs/heads/master
          path: .test/**
      - name: Initialize playwright snapshots
        if: ${{steps.cache.outputs.cache-hit != 'true' || inputs.update-snapshots }}
        run: bunx playwright test --update-snapshots
      - name: Run playwright tests
        continue-on-error: true
        id: playwright-step
        run: bun playwright
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: .test/spec/results/
          retention-days: 7
          overwrite: true
      - name: Fail if playwright tests failed
        if: ${{steps.playwright-step.outcome != 'success'}}
        run: exit 1